import type { DisruptionEvent } from './types';

export interface EnrichedDisruptionEvent extends DisruptionEvent {
  id: string;
  category: 'cyclone' | 'geopolitical' | 'pandemic' | 'congestion' | 'market';
  categoryLabel: string;
  affected_ports: string[];
  market_consequences: string;
  voyage_delay_days?: number;
  rate_impact_usd_day?: number;
  bdi_impact_pts?: number;
  mitigation_strategy: string;
}

export const HISTORICAL_EVENTS: EnrichedDisruptionEvent[] = [
  {
    id: 'gfc-2008',
    date: '2008-05-20',
    end_date: '2009-02-01',
    event: 'Global Financial Crisis & Shipping Collapse',
    type: 'ECONOMIC',
    category: 'market',
    categoryLabel: 'Market Extremes',
    impact: 'BDI crashed from historic peak 11,793 to 663 (-94%). Severe credit freeze, vessel lay-ups, and cancellations of shipbuilding orders globally.',
    icon: '📉',
    severity: 'CRITICAL',
    affected_regions: ['GLOBAL'],
    affected_ports: ['Paradip', 'Visakhapatnam', 'Haldia', 'Chennai', 'Singapore Hub', 'Rotterdam'],
    market_consequences: 'Capesize charter rates plunged from $233,000/day to below operating costs ($2,300/day). Widespread charter party defaults and counterparty bank freezes.',
    bdi_impact_pts: -11130,
    rate_impact_usd_day: -150000,
    mitigation_strategy: 'Enforce strict counterparty bank guarantee verification, shift from multi-year period fixtures to indexed spot contracts with sovereign guarantees.',
  },
  {
    id: 'bdi-low-2016',
    date: '2015-11-01',
    end_date: '2016-03-31',
    event: 'BDI Historic All-Time Low (290 points)',
    type: 'ECONOMIC',
    category: 'market',
    categoryLabel: 'Market Extremes',
    impact: 'BDI plunged to historic all-time low of 290 points on 11 Feb 2016 due to extreme dry bulk fleet oversupply and cooling Chinese raw material demand.',
    icon: '📉',
    severity: 'HIGH',
    affected_regions: ['GLOBAL'],
    affected_ports: ['Paradip', 'Dhamra', 'Visakhapatnam', 'Gangavaram', 'Port Hedland'],
    market_consequences: 'Capesize earnings collapsed to $2,700/day against daily OPEX of $6,500. Record ship demolition volumes and financial restructuring of global dry bulk shipowners.',
    bdi_impact_pts: -1200,
    rate_impact_usd_day: -18000,
    mitigation_strategy: 'Lock in multi-year long-term Contracts of Affreightment (COA) at rock-bottom base rates with fuel escalation clauses.',
  },
  {
    id: 'cyclone-fani-2019',
    date: '2019-04-26',
    end_date: '2019-05-05',
    event: 'Cyclone Fani (Cat-5 Landfall Puri)',
    type: 'WEATHER',
    category: 'cyclone',
    categoryLabel: 'Cyclones',
    impact: 'Category 5 equivalent cyclone made landfall near Puri, Odisha (wind gusts >205 km/h). Paradip, Dhamra, and Gopalpur ports suspended operations for 5-7 days with extensive berth, crane, and power infrastructure damage.',
    icon: '🌊',
    severity: 'CRITICAL',
    affected_regions: ['BAY_OF_BENGAL', 'EAST_INDIA'],
    affected_ports: ['Paradip', 'Dhamra', 'Gopalpur', 'Haldia Dock Complex'],
    market_consequences: '54 bulk carriers ordered to deep sea anchorage; demurrage liabilities exceeded $8.5M across East Coast importers. Coastal thermal coal supply halted for 10 days.',
    voyage_delay_days: 7,
    rate_impact_usd_day: 4200,
    bdi_impact_pts: 145,
    mitigation_strategy: 'Declare prompt Force Majeure notices under charterparty clause 21; divert incoming coal voyages to Visakhapatnam and Gangavaram deepwater berths.',
  },
  {
    id: 'covid-lockdown-2020',
    date: '2020-01-23',
    end_date: '2020-06-30',
    event: '2020 COVID Lockdowns & Port Disruptions',
    type: 'PANDEMIC',
    category: 'pandemic',
    categoryLabel: 'Pandemic',
    impact: 'Wuhan lockdown followed by worldwide restrictions. 14-day mandatory quarantine for ships calling from affected ports, severe discharge bottlenecks at Indian ports, industrial plant shutdowns, and worldwide seafarer crew change paralysis.',
    icon: '🦠',
    severity: 'CRITICAL',
    affected_regions: ['GLOBAL', 'EAST_INDIA', 'CHINA'],
    affected_ports: ['Paradip', 'Visakhapatnam', 'Haldia', 'Dhamra', 'Shanghai', 'Ningbo'],
    market_consequences: 'BDI crashed initially to 393 points in May 2020 before roaring back. Vessel wait times lengthened from 2.1 days to 14.8 days due to medical clearance protocols.',
    voyage_delay_days: 14,
    rate_impact_usd_day: -9500,
    bdi_impact_pts: -850,
    mitigation_strategy: 'Establish green corridor crew-change hubs, incorporate BIMCO infectious disease clauses, and maintain 45-day buffer stockpiles at coastal steel and power plants.',
  },
  {
    id: 'cyclone-amphan-2020',
    date: '2020-05-16',
    end_date: '2020-05-21',
    event: 'Cyclone Amphan (Super Cyclone Bay of Bengal)',
    type: 'WEATHER',
    category: 'cyclone',
    categoryLabel: 'Cyclones',
    impact: 'Super cyclone battered Bay of Bengal, striking West Bengal and Odisha coasts. Haldia Dock Complex and Sandheads lighterage suspended operations for 4 days; severe navigational mark dislocations in Hooghly river channel.',
    icon: '🌊',
    severity: 'HIGH',
    affected_regions: ['BAY_OF_BENGAL', 'EAST_INDIA'],
    affected_ports: ['Haldia Dock Complex', 'Sandheads Lighterage', 'Paradip', 'Dhamra'],
    market_consequences: 'Sandheads mother-daughter transshipment halted, trapping 180,000 MT coking coal aboard Supramax feeders. Siltation reduced Hooghly navigable draft by 0.6 meters for 3 weeks.',
    voyage_delay_days: 5,
    rate_impact_usd_day: 3100,
    bdi_impact_pts: 90,
    mitigation_strategy: 'Pre-berth deep draft bulkers at Paradip or Dhamra prior to tropical depression intensification; re-route lightering to sheltered anchorage.',
  },
  {
    id: 'port-congestion-2020-2022',
    date: '2020-08-01',
    end_date: '2022-04-30',
    event: 'Post-COVID Global Port Congestion Surge',
    type: 'LOGISTICS',
    category: 'congestion',
    categoryLabel: 'Congestion',
    impact: 'Consumer goods demand rebound caused historic container port queues in US West Coast (LA/Long Beach) and China. Multi-purpose and dry bulk capacity tied up in congestion, causing acute vessel availability shortages.',
    icon: '🚢',
    severity: 'HIGH',
    affected_regions: ['GLOBAL', 'PACIFIC', 'US_WEST_COAST', 'CHINA'],
    affected_ports: ['Los Angeles', 'Long Beach', 'Qingdao', 'Visakhapatnam', 'Singapore'],
    market_consequences: 'Up to 7.8% of the global dry bulk fleet immobilized at anchorage queues, generating an artificial vessel supply squeeze and driving charter rates to decade highs.',
    voyage_delay_days: 12,
    rate_impact_usd_day: 14500,
    bdi_impact_pts: 1650,
    mitigation_strategy: 'Employ AIS vessel queue tracking to book discharging windows at lesser-congested secondary berths like Gopalpur and Krishnapatnam.',
  },
  {
    id: 'ever-given-2021',
    date: '2021-03-23',
    end_date: '2021-03-29',
    event: '2021 Ever Given Suez Canal Grounding',
    type: 'MARITIME_ACCIDENT',
    category: 'congestion',
    categoryLabel: 'Congestion',
    impact: '20,124 TEU container ship ran aground blocking Suez Canal for 6 days. Trapped 369+ vessels and forced widespread diversions around the Cape of Good Hope (+10-14 voyage days), causing instant surge in charter rates.',
    icon: '🛑',
    severity: 'HIGH',
    affected_regions: ['SUEZ_CANAL', 'GLOBAL', 'MEDITERRANEAN', 'RED_SEA'],
    affected_ports: ['Port Said', 'Suez Anchorage', 'Visakhapatnam', 'Chennai', 'Paradip'],
    market_consequences: 'Over $9.6 billion of daily maritime trade blocked. Supramax and Ultramax spot charter fixtures jumped +22% in 72 hours due to delayed backhaul grain and steel voyages.',
    voyage_delay_days: 11,
    rate_impact_usd_day: 6800,
    bdi_impact_pts: 290,
    mitigation_strategy: 'Establish dual routing clauses in charter agreements allowing unilateral diversion around Cape of Good Hope with defined bunker adjustment compensations.',
  },
  {
    id: 'cyclone-tauktae-2021',
    date: '2021-05-14',
    end_date: '2021-05-19',
    event: 'Cyclone Tauktae (West Coast Severance)',
    type: 'WEATHER',
    category: 'cyclone',
    categoryLabel: 'Cyclones',
    impact: 'Powerful cyclone swept along India\'s west coast making landfall in Gujarat. Sinking of accommodation barge P305; coastal coal feeder movements from West Coast to southern/eastern plants halted.',
    icon: '🌊',
    severity: 'MEDIUM',
    affected_regions: ['ARABIAN_SEA', 'WEST_INDIA'],
    affected_ports: ['Kandla', 'Mundra', 'Mumbai', 'Chennai', 'Visakhapatnam'],
    market_consequences: 'Displaced coastal trade fleet, compelling state power utilities to urgently charter Supramax vessels on the East Coast to replenish inland plants.',
    voyage_delay_days: 4,
    rate_impact_usd_day: 1800,
    bdi_impact_pts: 65,
    mitigation_strategy: 'Activate domestic rail coastal transshipment bypass via East Coast corridors (Paradip to southern thermal utilities).',
  },
  {
    id: 'yantian-lockdown-2021',
    date: '2021-05-21',
    end_date: '2021-06-24',
    event: 'Yantian Port COVID-19 Lockdown',
    type: 'PANDEMIC',
    category: 'pandemic',
    categoryLabel: 'Pandemic',
    impact: 'Outbreak at Port of Yantian (Shenzhen) cut terminal productivity by ~70% for over a month. Created massive cargo backlogs across southern China ports and delayed bulk raw materials.',
    icon: '🔒',
    severity: 'MEDIUM',
    affected_regions: ['CHINA', 'GLOBAL'],
    affected_ports: ['Yantian', 'Shekou', 'Nansha', 'Paradip', 'Visakhapatnam'],
    market_consequences: 'Over 300 container and bulk ships waited up to 18 days outside the Pearl River delta. Congestion absorbed Handysize and Supramax breakbulk capacity.',
    voyage_delay_days: 8,
    rate_impact_usd_day: 3400,
    bdi_impact_pts: 180,
    mitigation_strategy: 'Shift discharge destinations to alternate northern ports (Caofeidian, Rizhao) and monitor provincial sanitary quarantine directives.',
  },
  {
    id: 'cyclone-yaas-2021',
    date: '2021-05-23',
    end_date: '2021-05-28',
    event: 'Cyclone Yaas (Landfall Dhamra-Balasore)',
    type: 'WEATHER',
    category: 'cyclone',
    categoryLabel: 'Cyclones',
    impact: 'Landfall south of Balasore, Odisha. Dhamra, Paradip, and Haldia completely suspended vessel operations, evacuated anchorages, and faced storm surge flooding; delayed 40+ inbound coal bulk carriers.',
    icon: '🌊',
    severity: 'HIGH',
    affected_regions: ['BAY_OF_BENGAL', 'EAST_INDIA'],
    affected_ports: ['Dhamra Port', 'Paradip Port', 'Haldia Dock Complex'],
    market_consequences: 'Extensive damage to conveyor galleries at Dhamra; coal discharge rates reduced 40% for 2 weeks post-storm. Pre-berthing delays climbed from 2.3 days to 7.6 days.',
    voyage_delay_days: 6,
    rate_impact_usd_day: 3900,
    bdi_impact_pts: 110,
    mitigation_strategy: 'Institute mandatory 48-hour cyclone evacuation protocols; reassign laycan windows under BIMCO storm contingency riders.',
  },
  {
    id: 'meishan-closure-2021',
    date: '2021-08-11',
    end_date: '2021-08-25',
    event: 'Ningbo-Zhoushan Meishan Terminal Closure',
    type: 'PANDEMIC',
    category: 'pandemic',
    categoryLabel: 'Pandemic',
    impact: 'China shut the world\'s third-busiest container/bulk hub terminal after single positive COVID test. Congestion spiked across East China Sea and tied up regional bulk and feeder vessels.',
    icon: '🔒',
    severity: 'MEDIUM',
    affected_regions: ['CHINA', 'GLOBAL'],
    affected_ports: ['Ningbo-Zhoushan', 'Shanghai', 'Visakhapatnam'],
    market_consequences: 'Anchorage waiting lines expanded to 80+ dry bulk and box carriers. Supramax regional trip rates jumped +16% on vessel shortages.',
    voyage_delay_days: 6,
    rate_impact_usd_day: 2800,
    bdi_impact_pts: 130,
    mitigation_strategy: 'Route raw material imports through southern alternatives and invoke flexible discharge port option riders.',
  },
  {
    id: 'cyclone-gulab-2021',
    date: '2021-09-24',
    end_date: '2021-09-28',
    event: 'Cyclone Gulab (Kalingapatnam Strike)',
    type: 'WEATHER',
    category: 'cyclone',
    categoryLabel: 'Cyclones',
    impact: 'Struck northern Andhra Pradesh coast near Kalingapatnam. Vizag, Gangavaram, and Gopalpur suspended cargo operations, delayed coal unloading by 48-72 hours.',
    icon: '🌊',
    severity: 'MEDIUM',
    affected_regions: ['BAY_OF_BENGAL', 'EAST_INDIA'],
    affected_ports: ['Visakhapatnam Port', 'Gangavaram Port', 'Gopalpur Port'],
    market_consequences: 'Gangavaram open-sea mechanised coal berths faced heavy swell disruptions (>3.8m), forcing 14 Capesize vessels to wait off fairway buoy.',
    voyage_delay_days: 3,
    rate_impact_usd_day: 2100,
    bdi_impact_pts: 55,
    mitigation_strategy: 'Utilise Vizag inner harbour sheltered berths for urgent discharges while holding outer harbour berths until swell attenuates.',
  },
  {
    id: 'bdi-peak-2021',
    date: '2021-10-07',
    end_date: '2021-10-31',
    event: '2021 BDI Peak (5,650 Points - 13 Year High)',
    type: 'MARKET',
    category: 'market',
    categoryLabel: 'Market Extremes',
    impact: 'BDI surged to 5,650 points, its highest level since 2008. Capesize daily earnings exceeded $86,000/day due to acute Chinese coal shortages, infrastructure stimulus, and widespread port congestion.',
    icon: '📈',
    severity: 'HIGH',
    affected_regions: ['GLOBAL'],
    affected_ports: ['Paradip', 'Visakhapatnam', 'Dhamra', 'Qingdao', 'Port Hedland'],
    market_consequences: 'Capesize earnings broke $86,950/day. High freight costs made import thermal coal prohibitively expensive for Indian coastal power plants, forcing Coal India to surge domestic rail dispatches.',
    voyage_delay_days: 0,
    rate_impact_usd_day: 48000,
    bdi_impact_pts: 3200,
    mitigation_strategy: 'Pivot chartering strategy to short spot contracts; avoid locking long-term fixtures near market highs. Hedging freight exposure via FFAs (Forward Freight Agreements).',
  },
  {
    id: 'indonesia-coal-ban-2022',
    date: '2022-01-01',
    end_date: '2022-01-31',
    event: 'Indonesia Sudden Coal Export Ban',
    type: 'REGULATORY',
    category: 'geopolitical',
    categoryLabel: 'Geopolitical',
    impact: 'Indonesian government banned all coal exports for 1 month to prioritize domestic PLN power plants. Stranded 400+ bulk carriers off Kalimantan (Samarinda, Banjarmasin); Indian coastal power plants scrambled for Australian/Mozambican coal, spiking Supramax rates.',
    icon: '⛔',
    severity: 'CRITICAL',
    affected_regions: ['INDONESIA', 'EAST_INDIA', 'GLOBAL'],
    affected_ports: ['Samarinda', 'Banjarmasin', 'Paradip', 'Visakhapatnam', 'Tuticorin', 'Ennore'],
    market_consequences: 'Sudden tonne-mile shift from short Indonesia-India trips (7-9 days) to long Australia/South Africa voyages (18-24 days). Panamax/Supramax spot rates surged by +35%.',
    voyage_delay_days: 12,
    rate_impact_usd_day: 8200,
    bdi_impact_pts: 440,
    mitigation_strategy: 'Diversify coal procurement across multi-origin supply contracts (Australia, South Africa, Russia, USA) to prevent single-country regulatory supply shocks.',
  },
  {
    id: 'russia-ukraine-war-2022',
    date: '2022-02-24',
    end_date: '2022-12-31',
    event: '2022 Russia-Ukraine War & Black Sea Blockade',
    type: 'GEOPOLITICAL',
    category: 'geopolitical',
    categoryLabel: 'Geopolitical',
    impact: 'Invasion closed Ukrainian ports and sparked Western sanctions on Russian coal and oil. Disrupted global dry bulk trade lanes; European buyers replaced Russian coal with imports from Australia, South Africa, and US, dramatically increasing global ton-mile demand.',
    icon: '⚔️',
    severity: 'CRITICAL',
    affected_regions: ['BLACK_SEA', 'EUROPE', 'GLOBAL', 'EAST_INDIA'],
    affected_ports: ['Odessa', 'Novorossiysk', 'Paradip', 'Visakhapatnam', 'Rotterdam'],
    market_consequences: 'Global dry bulk ton-mile demand grew by 3.2% overnight. Heavy discounts on Russian metallurgical and thermal coal led to record Indian imports into Dhamra and Paradip.',
    voyage_delay_days: 8,
    rate_impact_usd_day: 12600,
    bdi_impact_pts: 780,
    mitigation_strategy: 'Secure non-Western flag tonnage compliant with sanction screening, negotiate ruble-rupee payment mechanisms, and hedge against bunker price surges.',
  },
  {
    id: 'cyclone-asani-2022',
    date: '2022-05-07',
    end_date: '2022-05-12',
    event: 'Cyclone Asani (Andhra-Odisha Coast Swell)',
    type: 'WEATHER',
    category: 'cyclone',
    categoryLabel: 'Cyclones',
    impact: 'Bay of Bengal cyclone brought gale-force winds and heavy swells to Andhra Pradesh and Odisha coastlines. Vizag, Gangavaram, and Gopalpur suspended lightering and restricted vessel movements for 3 days.',
    icon: '🌊',
    severity: 'MEDIUM',
    affected_regions: ['BAY_OF_BENGAL', 'EAST_INDIA'],
    affected_ports: ['Visakhapatnam', 'Gangavaram', 'Gopalpur', 'Paradip'],
    market_consequences: 'Anchorage waiting time at Visakhapatnam rose by 3.4 days; pilotage suspended due to swell exceeding 3.5m in outer channels.',
    voyage_delay_days: 3,
    rate_impact_usd_day: 1900,
    bdi_impact_pts: 48,
    mitigation_strategy: 'Instruct incoming bulkers to slow-steam and loiter south of Sri Lanka until port clearance signals resume.',
  },
  {
    id: 'china-property-slump-2022',
    date: '2022-06-01',
    end_date: '2023-06-30',
    event: 'China Real Estate Crisis & Steel Output Slump',
    type: 'ECONOMIC',
    category: 'market',
    categoryLabel: 'Market Extremes',
    impact: 'Defaults among Chinese property developers (Evergrande, Country Garden) caused sharp contraction in construction activity. Steel mills reduced iron ore and coking coal intake, depressing Capesize rates in late 2022.',
    icon: '📉',
    severity: 'HIGH',
    affected_regions: ['CHINA', 'GLOBAL'],
    affected_ports: ['Qingdao', 'Tangshan', 'Paradip', 'Port Hedland'],
    market_consequences: 'Capesize spot earnings crashed below $4,000/day in September 2022. Surplus tonnage moved to Atlantic routes, reducing backhaul rates for Indian mineral exporters.',
    voyage_delay_days: 0,
    rate_impact_usd_day: -14000,
    bdi_impact_pts: -1420,
    mitigation_strategy: 'Leverage cheap spot Capesize rates to import high-grade coking coal from Australia and North America into East Coast steel mills.',
  },
  {
    id: 'cyclone-sitrang-2022',
    date: '2022-10-22',
    end_date: '2022-10-25',
    event: 'Cyclone Sitrang (Sandheads Lightering Halt)',
    type: 'WEATHER',
    category: 'cyclone',
    categoryLabel: 'Cyclones',
    impact: 'Made landfall near Barisal, Bangladesh. Triggered high storm surge across northern Bay of Bengal; Sandheads lighterage and Haldia river navigation closed for 3 days.',
    icon: '🌊',
    severity: 'MEDIUM',
    affected_regions: ['BAY_OF_BENGAL', 'EAST_INDIA'],
    affected_ports: ['Sandheads Lighterage', 'Haldia Dock Complex', 'Paradip'],
    market_consequences: 'Daughter barges unable to approach mother vessels at deep water anchorages; 12 Handymax vessels incurred demurrage charges averaging $18,000/day.',
    voyage_delay_days: 3,
    rate_impact_usd_day: 2200,
    bdi_impact_pts: 60,
    mitigation_strategy: 'Divert deep draft Panamax bulk carriers directly to Dhamra deepwater berths for full discharge rather than mid-sea lightering.',
  },
  {
    id: 'cyclone-mandous-2022',
    date: '2022-12-06',
    end_date: '2022-12-10',
    event: 'Cyclone Mandous (Tamil Nadu Landfall)',
    type: 'WEATHER',
    category: 'cyclone',
    categoryLabel: 'Cyclones',
    impact: 'Severe cyclonic storm crossed north Tamil Nadu coast near Mamallapuram. Affected southern Bay of Bengal shipping lanes and caused 3-day berthing delays at Chennai, Krishnapatnam, and Vizag.',
    icon: '🌊',
    severity: 'MEDIUM',
    affected_regions: ['BAY_OF_BENGAL', 'SOUTH_EAST_INDIA'],
    affected_ports: ['Chennai Port', 'Krishnapatnam Port', 'Ennore (Kamarajar)', 'Visakhapatnam'],
    market_consequences: 'Container and dry bulk berths closed for 72 hours; coastal feeder ships halted along Chennai-Paradip route.',
    voyage_delay_days: 3,
    rate_impact_usd_day: 1700,
    bdi_impact_pts: 45,
    mitigation_strategy: 'Reallocate coastal vessel discharge schedules; stage vessels in southern anchorage until port re-opens.',
  },
  {
    id: 'cyclone-mocha-2023',
    date: '2023-05-09',
    end_date: '2023-05-15',
    event: 'Cyclone Mocha (Cat-5 Myanmar/Bay of Bengal)',
    type: 'WEATHER',
    category: 'cyclone',
    categoryLabel: 'Cyclones',
    impact: 'Category 5 equivalent super cyclone struck Myanmar/Bangladesh border. Disruptive sea states and storm warnings prompted precautionary vessel clearances across East Coast Indian anchorages.',
    icon: '🌊',
    severity: 'HIGH',
    affected_regions: ['BAY_OF_BENGAL', 'EAST_INDIA'],
    affected_ports: ['Paradip', 'Dhamra', 'Haldia', 'Chittagong'],
    market_consequences: 'Bay of Bengal sea lanes shut down for 4 days; severe pilotage backlogs at Paradip and Haldia.',
    voyage_delay_days: 4,
    rate_impact_usd_day: 2900,
    bdi_impact_pts: 80,
    mitigation_strategy: 'Activate real-time weather routing services to guide vessels outside cyclone strike radius.',
  },
  {
    id: 'panama-drought-2023',
    date: '2023-06-01',
    end_date: '2024-04-30',
    event: '2023 Panama Canal Severe Drought Restrictions',
    type: 'WEATHER',
    category: 'congestion',
    categoryLabel: 'Congestion',
    impact: 'Severe El Niño drought caused Gatun Lake water levels to drop precipitously. ACP slashed daily vessel transits from 36 to 22 and cut max draft from 50ft to 44ft. US East Coast coal and grain bulkers diverted via Suez or Cape of Good Hope (+15-20 days).',
    icon: '☀️',
    severity: 'HIGH',
    affected_regions: ['PANAMA_CANAL', 'GLOBAL', 'US_EAST_COAST'],
    affected_ports: ['Balboa', 'Cristobal', 'Baltimore', 'Hampton Roads', 'Visakhapatnam', 'Paradip'],
    market_consequences: 'Panamax auction transit slots sold for over $4 million. US coal voyages to India added 16 sailing days via Cape, soaking up 4.1% of global Panamax fleet and driving daily hire up +38%.',
    voyage_delay_days: 16,
    rate_impact_usd_day: 8900,
    bdi_impact_pts: 520,
    mitigation_strategy: 'Substitute US metallurgical coal with Australian and Indonesian blends, or book Capesize transshipment via South Africa.',
  },
  {
    id: 'cyclone-biparjoy-2023',
    date: '2023-06-06',
    end_date: '2023-06-19',
    event: 'Cyclone Biparjoy (Arabian Sea)',
    type: 'WEATHER',
    category: 'cyclone',
    categoryLabel: 'Cyclones',
    impact: 'Long-lived cyclone in the Arabian Sea made landfall near Jakhau Port, Gujarat. Disrupted western coastal logistics and delayed return ballast voyages of Indian coastal bulkers.',
    icon: '🌊',
    severity: 'MEDIUM',
    affected_regions: ['ARABIAN_SEA', 'WEST_INDIA'],
    affected_ports: ['Kandla', 'Mundra', 'Pipavav', 'Paradip'],
    market_consequences: 'Stranded 85 vessels at Gujarat ports for 10 days, delaying repositioning of dry bulk vessels to East Coast mineral loading berths.',
    voyage_delay_days: 6,
    rate_impact_usd_day: 2300,
    bdi_impact_pts: 70,
    mitigation_strategy: 'Rebalance coastal charter fleet between East and West coasts using flexible laycan window agreements.',
  },
  {
    id: 'cyclone-midhili-2023',
    date: '2023-11-15',
    end_date: '2023-11-18',
    event: 'Cyclone Midhili (North Bay of Bengal)',
    type: 'WEATHER',
    category: 'cyclone',
    categoryLabel: 'Cyclones',
    impact: 'Deep depression intensified into cyclonic storm over Bay of Bengal making landfall in Bangladesh. Interrupted lightering at Sandheads and delayed berthing at Haldia and Paradip.',
    icon: '🌊',
    severity: 'LOW',
    affected_regions: ['BAY_OF_BENGAL', 'EAST_INDIA'],
    affected_ports: ['Haldia', 'Sandheads', 'Paradip'],
    market_consequences: 'Minor berthing delays (36 hours) and brief swell surge in Hooghly river approaches.',
    voyage_delay_days: 2,
    rate_impact_usd_day: 1100,
    bdi_impact_pts: 30,
    mitigation_strategy: 'Maintain short-notice tug readiness and buffer berthing schedules by 48 hours.',
  },
  {
    id: 'red-sea-crisis-2023',
    date: '2023-11-19',
    end_date: '2026-12-31',
    event: '2023 Red Sea Crisis & Bab-el-Mandeb Blockade',
    type: 'GEOPOLITICAL',
    category: 'geopolitical',
    categoryLabel: 'Geopolitical',
    impact: 'Houthi anti-ship missile and drone attacks forced commercial shipping to abandon the Suez Canal / Bab-el-Mandeb corridor. Dry bulk and container vessels rerouted around the Cape of Good Hope (+3,500 nm, +10-14 days), sharply escalating bunker costs, transit times, and war-risk premiums for US coal to India.',
    icon: '⚔️',
    severity: 'CRITICAL',
    affected_regions: ['RED_SEA', 'SUEZ_CANAL', 'BAB_EL_MANDEB', 'GLOBAL'],
    affected_ports: ['Bab-el-Mandeb Strait', 'Suez Canal', 'Visakhapatnam', 'Paradip', 'Dhamra', 'Cape Town Bunker Hub'],
    market_consequences: 'Global dry bulk tonne-miles jumped +5.2%. Bunker consumption per voyage increased by 380-600 MT ($240,000+ per voyage). Capesize & Panamax rates spiked +40-65% in Q1 2024.',
    voyage_delay_days: 14,
    rate_impact_usd_day: 11500,
    bdi_impact_pts: 890,
    mitigation_strategy: 'Route Atlantic coal via Cape of Good Hope with advance bunker hedging at Singapore or Durban; request War Risk insurance subsidies for strategic national energy cargoes.',
  },
  {
    id: 'cyclone-michaung-2023',
    date: '2023-12-02',
    end_date: '2023-12-06',
    event: 'Cyclone Michaung (Chennai/Andhra Deluge)',
    type: 'WEATHER',
    category: 'cyclone',
    categoryLabel: 'Cyclones',
    impact: 'Battered Tamil Nadu and Andhra Pradesh coast, making landfall near Bapatla. Caused catastrophic flooding in Chennai and shut cargo operations at Krishnapatnam, Vizag, and Gangavaram for 4 days with high swell.',
    icon: '🌊',
    severity: 'HIGH',
    affected_regions: ['BAY_OF_BENGAL', 'EAST_INDIA'],
    affected_ports: ['Chennai', 'Ennore', 'Krishnapatnam', 'Visakhapatnam', 'Gangavaram'],
    market_consequences: 'Chennai port rail yards flooded, disrupting intermodal rake movements for 8 days. Demurrage incurred on 28 waiting dry bulk vessels.',
    voyage_delay_days: 5,
    rate_impact_usd_day: 3200,
    bdi_impact_pts: 95,
    mitigation_strategy: 'Reroute rake loading to Visakhapatnam and Gangavaram rail heads and declare inland transport Force Majeure.',
  },
  {
    id: 'baltimore-bridge-2024',
    date: '2024-03-26',
    end_date: '2024-06-10',
    event: 'Baltimore Francis Scott Key Bridge Collapse',
    type: 'MARITIME_ACCIDENT',
    category: 'congestion',
    categoryLabel: 'Congestion',
    impact: 'Container ship Dali collided with bridge support, collapsing span and blocking the Patapsco River navigation channel. Shut the Port of Baltimore (second-largest US coal export hub, ~28M MT/yr) for 2.5 months; redirected met and thermal coal exports to Hampton Roads terminals, causing rail and terminal congestion.',
    icon: '🌉',
    severity: 'HIGH',
    affected_regions: ['US_EAST_COAST', 'GLOBAL'],
    affected_ports: ['Port of Baltimore', 'Hampton Roads (Norfolk/Newport News)', 'Visakhapatnam', 'Paradip'],
    market_consequences: 'Cut off ~2.5 million MT/month of metallurgical and thermal coal exports to India. Norfolk rail yards bottlenecked with 14-day train turnaround delays, pushing Capesize Atlantic rates higher.',
    voyage_delay_days: 10,
    rate_impact_usd_day: 5400,
    bdi_impact_pts: 210,
    mitigation_strategy: 'Immediately substitute stranded Baltimore met coal contracts with Australian Bowen Basin or Canadian export blends.',
  },
  {
    id: 'cyclone-remal-2024',
    date: '2024-05-24',
    end_date: '2024-05-28',
    event: '2024 Cyclone Remal (Sagar Island / Haldia Halt)',
    type: 'WEATHER',
    category: 'cyclone',
    categoryLabel: 'Cyclones',
    impact: 'Severe cyclonic storm made landfall at Sagar Island, West Bengal / Khepupara, Bangladesh. Haldia Dock Complex halted operations for 48 hours; Sandheads lighterage suspended for 4 days; vessel traffic in Hooghly river suspended.',
    icon: '🌊',
    severity: 'HIGH',
    affected_regions: ['BAY_OF_BENGAL', 'EAST_INDIA'],
    affected_ports: ['Haldia Dock Complex', 'Sandheads Lighterage', 'Kolkata Dock System', 'Paradip'],
    market_consequences: 'Sandheads lighterage shut down completely. 16 Supramax coal vessels grounded on anchor or forced to hold position at deep sea; river pilotage backlogged for 1 week.',
    voyage_delay_days: 5,
    rate_impact_usd_day: 2800,
    bdi_impact_pts: 85,
    mitigation_strategy: 'Divert deep-draft daughter vessels to Paradip or Dhamra to avoid Hooghly draft siltation restrictions.',
  },
  {
    id: 'ila-strike-2024',
    date: '2024-10-01',
    end_date: '2024-10-04',
    event: '2024 ILA US Port Strike (East & Gulf Coasts)',
    type: 'LABOR',
    category: 'congestion',
    categoryLabel: 'Congestion',
    impact: '45,000 dockworkers walked out across 36 major ports from Maine to Texas. Complete shutdown of container and multi-commodity terminals halted regional cargo movements and created a multi-week vessel backlog along the US Atlantic seaboard.',
    icon: '🛑',
    severity: 'HIGH',
    affected_regions: ['US_EAST_COAST', 'US_GULF', 'GLOBAL'],
    affected_ports: ['New York/New Jersey', 'Savannah', 'Houston', 'New Orleans', 'Visakhapatnam'],
    market_consequences: 'Over 140 ships anchored outside US ports within 72 hours. Freight forwarders rushed to book breakbulk alternatives, driving Handysize and Supramax spot fixture premiums +18%.',
    voyage_delay_days: 6,
    rate_impact_usd_day: 4600,
    bdi_impact_pts: 240,
    mitigation_strategy: 'Include strike risk riders with extended laytime clauses; reroute critical breakbulk cargo through Canadian or West Coast gateways.',
  },
  {
    id: 'cyclone-dana-2024',
    date: '2024-10-23',
    end_date: '2024-10-26',
    event: '2024 Cyclone Dana (Dhamra-Paradip Core Strike)',
    type: 'WEATHER',
    category: 'cyclone',
    categoryLabel: 'Cyclones',
    impact: 'Severe cyclonic storm made landfall between Dhamra and Paradip (Habalikhati Nature Camp). Paradip and Dhamra ports suspended all cargo operations, ordered vessels to anchor at deep sea, and shut railway dispatch rakes for 3 days.',
    icon: '🌊',
    severity: 'HIGH',
    affected_regions: ['BAY_OF_BENGAL', 'EAST_INDIA'],
    affected_ports: ['Paradip Port', 'Dhamra Port', 'Gopalpur Port'],
    market_consequences: 'Complete evacuation of 24 berths across Paradip and Dhamra. Inbound coal and iron ore dispatch rakes halted by East Coast Railway, backing up 1.2M MT of bulk material at port stockyards.',
    voyage_delay_days: 4,
    rate_impact_usd_day: 3500,
    bdi_impact_pts: 105,
    mitigation_strategy: 'Clear stockyards 72 hours prior to landfall; anchor laden bulkers in deep water (>25m depth) outside storm surge envelope.',
  },
  {
    id: 'cyclone-fengal-2024',
    date: '2024-11-27',
    end_date: '2024-12-03',
    event: 'Cyclone Fengal (Tamil Nadu/Puducherry Inundation)',
    type: 'WEATHER',
    category: 'cyclone',
    categoryLabel: 'Cyclones',
    impact: 'Cyclonic storm crossed north Tamil Nadu and Puducherry coasts, delivering unprecedented torrential downpours (up to 500mm in 24h) and rough sea states. Delayed bulk vessel berthing and discharging across East Coast ports from Chennai to Vizag.',
    icon: '🌊',
    severity: 'MEDIUM',
    affected_regions: ['BAY_OF_BENGAL', 'SOUTH_EAST_INDIA'],
    affected_ports: ['Chennai', 'Ennore', 'Puducherry', 'Krishnapatnam', 'Visakhapatnam'],
    market_consequences: 'Extreme waterlogging disrupted discharge operations and terminal cranes for 96 hours; berth wait times increased by 4.2 days across Tamil Nadu terminals.',
    voyage_delay_days: 4,
    rate_impact_usd_day: 2400,
    bdi_impact_pts: 65,
    mitigation_strategy: 'Engage covered hatch discharge protocols where feasible and divert non-containerized bulkers north to Gangavaram.',
  },
  {
    id: 'southwest-monsoon-annual',
    date: '2024-06-01',
    end_date: '2024-09-30',
    event: 'Southwest Monsoon Season (Annual Recurring)',
    type: 'SEASONAL',
    category: 'cyclone',
    categoryLabel: 'Cyclones',
    impact: 'Annual meteorological cycle causing high swells (>3.5m), persistent squalls, and rough seas across the Bay of Bengal. Open roadsteads (Gopalpur) and riverine approaches (Haldia/Sandheads) experience reduced discharge rates (down 20-35%), frequent lightering halts, and prolonged anchorage waiting.',
    icon: '🌧️',
    severity: 'HIGH',
    affected_regions: ['BAY_OF_BENGAL', 'EAST_INDIA', 'ARABIAN_SEA'],
    affected_ports: ['Gopalpur', 'Haldia', 'Sandheads', 'Paradip', 'Visakhapatnam'],
    market_consequences: 'Overall port throughput drops by 15-25% between June and August. Supramax and Handymax coastal fixtures price in a $1,500-$2,500/day weather premium.',
    voyage_delay_days: 5,
    rate_impact_usd_day: 2000,
    bdi_impact_pts: 75,
    mitigation_strategy: 'Shift laycan allocations to enclosed dock basins (Visakhapatnam Inner Harbour, Paradip Central Dock) and build pre-monsoon coal reserves at power plants.',
  },
  {
    id: 'peak-dry-bulk-season-annual',
    date: '2024-10-01',
    end_date: '2025-03-31',
    event: 'Peak Dry Bulk Import Season (Annual Recurring)',
    type: 'SEASONAL',
    category: 'market',
    categoryLabel: 'Market Extremes',
    impact: 'Post-monsoon industrial replenishment window. Indian thermal power utilities and steel plants (SAIL, Tata, JSW) aggressively ramp up seaborne coal restocking. Berth occupancy across Paradip, Dhamra, and Vizag reaches 85-95% with elevated pre-berthing wait times.',
    icon: '📈',
    severity: 'MEDIUM',
    affected_regions: ['EAST_INDIA', 'GLOBAL'],
    affected_ports: ['Paradip', 'Visakhapatnam', 'Dhamra', 'Gangavaram', 'Haldia'],
    market_consequences: 'High berth occupancy leads to average pre-berthing waiting times of 4.5 - 7.2 days at Paradip and Vizag. Spot charter rates for Indian East Coast routes trade at a 15-20% premium over Pacific basket.',
    voyage_delay_days: 4,
    rate_impact_usd_day: 3800,
    bdi_impact_pts: 310,
    mitigation_strategy: 'Secure medium-term indexed contracts of affreightment (COA) with guaranteed discharge berths or demurrage sharing caps ahead of October.',
  },
];
